"0","library(janitor)"
"0",""
"0","covid_healthcare_costs <- left_join(avghealthcarecost2022, rate2021, by=c(""GeoID"", ""Geography.Name"",""Sits.in.State"")) %>% "
"0","  row_to_names(row_number = 1) %>% "
"0","  clean_names() %>% "
"0","  rename("
"0","    county = geo_id_name,"
"0","    state = sitsin_state,"
"0","    county_fips = geo_id,"
"0","    avg_healthcarecost = totslf_avg,"
"0","    year = time_frame,"
"0","    avg_covidcases = pc_av7dy_2wk_cases,"
"0","    week_start = time_frame_2) %>% "
"0","  select(""county"",""state"", ""county_fips"", ""avg_healthcarecost"", ""year"", ""avg_covidcases"", ""week_start"") %>% "
"0","  drop_na() %>% "
"0","  mutate(avg_healthcarecost = as.numeric(avg_healthcarecost),"
"0","         avg_covidcases = as.numeric(avg_covidcases)) "
"2","Warning:"
"2"," Row 1 does not provide unique names. Consider running clean_names() after row_to_names().
"
"2","Warning:"
"2"," [38;5;232mThere were 2 warnings in `mutate()`.
The first warning was:[39m
[38;5;232m[36mâ„¹[38;5;232m In argument: `avg_healthcarecost = as.numeric(avg_healthcarecost)`.[39m
Caused by warning:
[33m![39m NAs introduced by coercion
[38;5;232m[36mâ„¹[38;5;232m Run ]8;;ide:run:dplyr::last_dplyr_warnings()dplyr::last_dplyr_warnings()]8;; to see the 1 remaining warning.[39m
"
"0","  "
"0","covid_healthcare_costs"
